# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-21 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordMapCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sense', models.CharField(max_length=64)),
                ('selected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WordProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemma', models.CharField(max_length=32)),
                ('ont_type', models.CharField(max_length=64)),
                ('solved', models.BooleanField(default=False)),
                ('is_name', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='wordmapcandidate',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SenseList.WordProposal'),
        ),
    ]
