# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-22 21:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SenseList', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='wordmapcandidate',
            name='selected',
        ),
        migrations.AddField(
            model_name='candidateselection',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SenseList.WordMapCandidate'),
        ),
        migrations.AddField(
            model_name='candidateselection',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SenseList.WordProposal'),
        ),
        migrations.AddField(
            model_name='candidateselection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
